version: '3.3'

services:
  web-dashboard:
    build: ./
    volumes:
      - .:/usr/src/web 
    ports:
      - "5001:3000"
    depends_on: 
      - redis 
  redis:
    image: redis
    ports:
      - "6379:6379"
networks:
  fontend:
    driver: bridge